# Generated by Django 3.2.16 on 2022-11-26 11:52

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='Количество уровней торта')),
                ('form', models.IntegerField(choices=[(1, 'Круг'), (2, 'Квадрат'), (3, 'Прямоугольник')], verbose_name='Форма торта')),
                ('toppings', models.IntegerField(choices=[(1, 'Без'), (2, 'Белый соус'), (3, 'Карамельный'), (4, 'Кленовый'), (5, 'Черничный'), (6, 'Молочный шоколад'), (7, 'Клубничный')], verbose_name='Топпинг')),
                ('berries', models.IntegerField(choices=[(1, 'нет'), (2, 'Ежевика'), (3, 'Малина'), (4, 'Голубика'), (5, 'Клубника')], default=('1', 'нет'), verbose_name='Ягоды')),
                ('decors', models.IntegerField(choices=[(1, 'нет'), (2, 'Фисташки'), (3, 'Безе'), (4, 'Фундук'), (5, 'Пекан'), (6, 'Маршмеллоу'), (7, 'Марципан')], default=('1', 'нет'), verbose_name='Декор')),
                ('words', models.CharField(blank=True, max_length=50, verbose_name='Надпись')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
            ],
            options={
                'verbose_name': 'cake',
                'verbose_name_plural': 'cakes',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала действия промокода')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия промокода')),
                ('discount', models.FloatField(verbose_name='Процент скидки')),
                ('value', models.CharField(max_length=50, verbose_name='Текст промокода')),
            ],
            options={
                'verbose_name': 'complaint',
                'verbose_name_plural': 'complaints',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=70, unique=True, verbose_name='Email')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(verbose_name='Дата и время заказа')),
                ('address', models.TextField(help_text='г.Ярославль, ул. Звёздная, д.5 кв.4', verbose_name='Адрес доставки')),
                ('delivery_datetime', models.DateTimeField(verbose_name='Дата и время доставки')),
                ('total', models.IntegerField(null=True, verbose_name='Стоимость заказа')),
                ('delivery_comment', models.TextField(default='Отсутствует', verbose_name='Комментарий для курьера')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake.cake', verbose_name='Заказанный торт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Текст жалобы')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='cake.order', verbose_name='Заказ, на который жалуются')),
            ],
            options={
                'verbose_name': 'complaint',
                'verbose_name_plural': 'complaints',
            },
        ),
    ]
