# Generated by Django 3.2.16 on 2022-11-23 17:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three')], default=0, verbose_name='Количество уровней торта')),
                ('form', models.CharField(choices=[('ROUND', 'Round'), ('SQUARE', 'Square'), ('RECTANGLE', 'Rectangle'), ('NO', 'No')], default='NO', max_length=50, verbose_name='Форма торта')),
                ('toppings', models.CharField(choices=[('WITHOUT', 'Without'), ('WHITE', 'White'), ('CARAMEL', 'Caramel'), ('MAPLE', 'Maple'), ('BLUEBERRY', 'Blueberry'), ('MILKCHOCKOLATE', 'Milkchockolate'), ('STAWBERRY', 'Stawberry'), ('NO', 'No')], default='NO', max_length=50, verbose_name='Топпинг')),
                ('berries', models.CharField(choices=[('STAWBERRY', 'Stawberry'), ('BLUEBERRY', 'Blueberry'), ('RAPSBERRY', 'Rapsberry'), ('BLACKBERRY', 'Blackberry'), ('NO', 'No')], default='NO', max_length=50, verbose_name='Ягоды')),
                ('decors', models.CharField(choices=[('PISTACHIO', 'Pistachio'), ('MERINGUE', 'Meringue'), ('HAZELNUT', 'Hazelnut'), ('PECAN', 'Pecan'), ('MARSHMALLOW', 'Marshmallow'), ('MARZIPAN', 'Marzipan'), ('NO', 'No')], default='NO', max_length=50, verbose_name='Декор')),
                ('words', models.CharField(blank=True, max_length=50, verbose_name='Надпись')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала действия промокода')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия промокода')),
                ('discount', models.FloatField(verbose_name='Процент скидки')),
                ('value', models.CharField(max_length=50, verbose_name='Текст промокода')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=70, unique=True, verbose_name='Email')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(verbose_name='Дата и время заказа')),
                ('address', models.TextField(help_text='г.Ярославль, ул. Звёздная, д.5 кв.4', verbose_name='Адрес доставки')),
                ('delivery_datetime', models.DateTimeField(verbose_name='Дата и время доставки')),
                ('total', models.IntegerField(verbose_name='Стоимость заказа')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake.cake', verbose_name='Заказанный торт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Текст жалобы')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='cake.order', verbose_name='Заказ, на который жалуются')),
            ],
        ),
    ]
