# Generated by Django 3.2.16 on 2022-11-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'promocode', 'verbose_name_plural': 'promocodes'},
        ),
    ]
